require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SmartMerch/smcamera_swiftios.git'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorClipboard', :path => '../../node_modules/@capacitor/clipboard'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapSm', :path => '../../node_modules/cap-sm'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'smcamera_ios'
  pod 'CapSm', :path => '../../node_modules/cap-sm'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
